### ISSUE TITLE
Return timezone of the state where AED is located

### ISSUE THREAD

**Issue by starsep** [openstreetmap-polska/openaedmap-backend#11]
It is used for calculating whether AED is currently opened together with `opening_hours`.
Frontend uses Nominatim reverse geocoding API + timezone library to get this information.
It could be precalculated and kept in the database.
It should be recalculcated (cron job?) as borders of countries/states/timezones change.

**Comment by Zaczero** [comment]
Added in https://github.com/openstreetmap-polska/openaedmap-backend/commit/a636ca37b2e65821bf8fec4cabfd0c37b6ff9e5d.

If a timezone fails to resolve, a <kbd>null</kbd> value is returned so please check for that. timezone_name is more reliable than timezone_offset but harder to use. When timezone_name resolves correctly, timezone_offset may fail, if such timezone is unknown to the server. When timezone_name fails to resolve, timezone_offset will fail too.

Example response:

```json
{
    "version": 0.6,
    "copyright": "OpenStreetMap and contributors",
    "attribution": "http://www.openstreetmap.org/copyright",
    "license": "http://opendatacommons.org/licenses/odbl/1-0/",
    "elements": [
        {
            "@timezone_name": "Europe/Warsaw",
            "@timezone_offset": "UTC+02:00",
            "type": "node",
            "id": 9453974307,
            "lat": 51.82957,
            "lon": 20.27686,
            "tags": {
                "access": "private",
                "defibrillator:location": "Samochód ratowniczo-gaśniczy",
                "defibrillator:location:en": "Rescue and firefighting car",
                "emergency": "defibrillator",
                "operator": "OSP Kurzeszyn"
            },
            "version": 0
        }
    ]
}
```
