### ISSUE TITLE
Enable gzip for https://back.openaedmap.org/data/

### ISSUE THREAD

**Issue by starsep** [openstreetmap-polska/openaedmap-backend#12]
It's configured in https://github.com/openstreetmap-polska/openaedmap-backend/blob/be5734fed0f6dbf8f1975dd5e4adbd30de6265ec/nginx/nginx-proxy-prod.conf#L58
According to my testing it doesn't work.
Example url: https://back.openaedmap.org/data/world.geojson
Useful tool: https://www.whatsmyip.org/http-compression-test/

**Comment by Zaczero** [comment]
Fixed in https://github.com/openstreetmap-polska/openaedmap-backend/commit/53491dc9cda47a2e88065cd82ba130a9180f7d13
