### ISSUE TITLE
Provide license and author info of wikimedia_commons photos

### ISSUE THREAD

**Issue by starsep** [openstreetmap-polska/openaedmap-backend#51]
Related to #47 
Example AED: https://www.openstreetmap.org/node/11081641408
It has image: https://commons.wikimedia.org/wiki/File:Defibrillatore%20Comunale%204.jpg?uselang=en
License is CC BY-SA 4.0 so we have to include attribution
At the moment information about author and license is missing in https://openaedmap.org/api/v1/node/11081641408

**Comment by Zaczero** [comment]
The backend does not use the Wikimedia Commons API to fetch the images.

It actually [uses](https://github.com/openstreetmap-polska/openaedmap-backend/blob/61002361d768efb15858b6f623ed513ab4c3549d/api/v1/photos.py#L87) the [Open Graph Protocol](https://ogp.me/), which is a standard way for a website to provide information (title, description, image) to other websites for them to generate a preview for a particular link.

You can see the protocol in action on other applications such as:

**OpenStreetMap Community (Discourse)**

![image](https://github.com/openstreetmap-polska/openaedmap-backend/assets/10835147/c35062d0-7de1-4bbf-b46c-c70035f552b8)

**Discord**

![image](https://github.com/openstreetmap-polska/openaedmap-backend/assets/10835147/73a80f1d-f8e8-44b3-b47e-21191e23d8e4)

*and thousands of other applications, including Facebook, Twitter, Google...*

In this case, the website providing such protocol (Wikimedia Commons) is responsible for using images they have the right to, and in a way that would not violate the license. It appears indeed that there is a potential license violation (missing license text, missing attribution) on images served by the Wikimedia Commons service - perhaps we should let them know about it.

On our side, I have [added](https://github.com/openstreetmap-polska/openaedmap-backend/commit/61002361d768efb15858b6f623ed513ab4c3549d) X-Image-Source (url) response header to all proxied images so it can be displayed together with the image. I suggest we display the link (potentially trimmed as links can be VERY LONG) on the left side, and a small information text "(i) Images might be subject to copyright" on the right.

![image](https://github.com/openstreetmap-polska/openaedmap-backend/assets/10835147/16148691-eb80-4101-aa1e-be9957a178f3)

![image](https://github.com/openstreetmap-polska/openaedmap-backend/assets/10835147/ab175411-c2de-4ea1-a5ec-9fd0ba6b6de1)

That's how other websites deal with unknown license information (for inspiration):

**Brave Search**

![image](https://github.com/openstreetmap-polska/openaedmap-backend/assets/10835147/3d4e73cd-e6fd-49c2-86dc-363ac931de59)

**Google**

![image](https://github.com/openstreetmap-polska/openaedmap-backend/assets/10835147/a87e6e77-87cb-4de9-8af2-fb0b4f543a85)

**Comment by starsep** [comment]
It would be easier if information from X-Image-Source header would be included in AED API e.g. https://openaedmap.org/api/v1/node/11081641408

Currently image url is passed to ImageGallery.
Browser is fetching image directly and I don't have access to HTTP headers for this request.

Alternatively I could make another `HEAD` request for image to get headers without body.

**Comment by Zaczero** [comment]
Done, returned in `@photo_source`

**Comment by Zaczero** [comment]
Closed in favor https://github.com/openstreetmap-polska/openaedmap-frontend/issues/216
