### ISSUE TITLE
Version returned is 0

### ISSUE THREAD

**Issue by starsep** [openstreetmap-polska/openaedmap-backend#53]
Example:
https://openaedmap.org/api/v1/node/5140047708
returns
```
{
    "version": 0.6,
    "copyright": "OpenStreetMap and contributors",
    "attribution": "https://www.openstreetmap.org/copyright",
    "license": "https://opendatacommons.org/licenses/odbl/1-0/",
    "elements": [
        {
            "@photo_id": null,
            "@photo_url": null,
            "@timezone_name": "Europe/Warsaw",
            "@timezone_offset": "UTC+01:00",
            "type": "node",
            "id": 5140047708,
            "lat": 52.2399553,
            "lon": 21.0134473,
            "tags": {
                "defibrillator:location": "W hotelu Sofitel",
                "emergency": "defibrillator",
                "operator": "Sofitel"
            },
            "version": 0
        }
    ]
}
```
I would expect `"version": 2`
![image](https://github.com/openstreetmap-polska/openaedmap-backend/assets/2798728/b205afa9-f367-4945-b196-279eaea145d0)
https://www.openstreetmap.org/node/5140047708

**Comment by ttomasz** [comment]
Looks like this is hardcoded: https://github.com/openstreetmap-polska/openaedmap-backend/blob/61002361d768efb15858b6f623ed513ab4c3549d/api/v1/node.py#L98

**Comment by Zaczero** [comment]
Why do we need the version? The original idea was that there is no guarantee about the returned version, so we might as well return 0 to prevent others from using it accidentally. I can add version support if needed.

**Comment by Zaczero** [comment]
I now understand that frontend depends on this value to perform edits. Fixed it.
