### ISSUE TITLE
Add to Taginfo Projects

### ISSUE THREAD

**Issue by danieldegroot2** [openstreetmap-polska/openaedmap-backend#6]
Show the OpenStreetMap community what [data](https://wiki.openstreetmap.org/wiki/Tags) you are using. Add your project to the [list](https://taginfo.openstreetmap.org/projects) of [Taginfo Projects](https://github.com/taginfo/taginfo-projects).

(similar to [aed_mapa](https://taginfo.openstreetmap.org/projects/aed_mapa))

**Comment by ttomasz** [comment]
https://github.com/taginfo/taginfo-projects/pull/144
