### ISSUE TITLE
Photo not showing up

### ISSUE THREAD

**Issue by filip-769** [openstreetmap-polska/openaedmap-backend#73]
I uploaded a photo (twice) and the link is just 404 error.

https://openaedmap.org/?node_id=11793349907

**Comment by Zaczero** [comment]
Hey! Can you share the photo here? It will make it easier to test it :-)

**Comment by Zaczero** [comment]
I managed to locate your file! I fixed it: https://openaedmap.org/api/v1/photos/view/-H4JdjWmfRZZxQD6hvom3g.webp and I also found and fixed the issue. Upload should work as expected now :slightly_smiling_face:. Thanks for reporting it!

**Comment by filip-769** [comment]
thanks for the quick fix. i think this can be closed
